did_django_twilio_api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('users.urls', namespace="users")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
	
	path('', views.sign_in, name="sign-in"),
	url(r'^sign-up', views.sign_up, name="sign-up"),
	url(r'^sign-out', views.sign_out, name="sign-out"),
	url(r'^forgotten-password', views.forgotten_password, name="forgotten-password"),
	url(r'^email', views.email, name="email"),
	url(r'^account', views.account, name="account"),
	url(r'^verification/(?P<uidb64>.+)/(?P<token>.+)/$',views.verification, name='verification'),
	]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from . choices import COUNTRIES

'''
Our UserProfile model extends the built-in Django User Model
'''
class UserProfile(models.Model):
	
	updated = models.DateTimeField(auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	telephone = models.CharField(max_length=15, null=True, blank=True)
	address = models.CharField(verbose_name="Address",max_length=100, null=True, blank=True)
	town = models.CharField(verbose_name="Town/City",max_length=100, null=True, blank=True)
	county = models.CharField(verbose_name="County",max_length=100, null=True, blank=True)
	post_code = models.CharField(verbose_name="Post Code",max_length=8, null=True, blank=True)
	country = models.CharField(verbose_name="Country",max_length=100, null=True, blank=True, choices=COUNTRIES)
	is_active = models.BooleanField(default = True)

	email_verified = models.BooleanField(default = False)
	two_step_active = models.BooleanField(default = True)

	def __str__(self):
		return f'{self.user}'



'''
Our UserToken model is used to store verification tokens generated by users.
'''
class UserToken(models.Model):
	
	updated = models.DateTimeField(auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	token = models.CharField(max_length=100, null=True, blank=True)
	two_step_code = models.CharField(max_length=6, null=True, blank=True)
	
	#used to change the object type
	is_email = models.BooleanField(default= False)
	is_password = models.BooleanField(default = False)
	is_sms = models.BooleanField(default = False)

	is_active = models.BooleanField(default = True)

	def __str__(self):
		return f'{self.user}'

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm, PasswordResetForm
from django.contrib.auth.models import User
from django import forms
from .models import UserProfile, UserToken
from .choices import COUNTRIES

# DOCS - https://docs.djangoproject.com/en/1.8/_modules/django/contrib/auth/forms/

'''
Form that uses built-in UserCreationForm to handel user creation
'''
class UserForm(UserCreationForm):
	first_name = forms.CharField(max_length=30, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Your first name..'}))
	last_name = forms.CharField(max_length=30, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Your last name..'}))
	username = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Email..'}))
	password1 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Password..','class':'password'}))
	password2 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Confirm Password..','class':'password'}))

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'password1', 'password2', )




'''
Form that uses built-in AuthenticationForm to handel user auth
'''
class AuthForm(AuthenticationForm):
	
	username = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Email..'}))
	password = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Password..','class':'password'}))

	class Meta:
		model = User
		fields = ('username','password', )




'''
Basic model-form for our user profile that extends Django user model.
'''
class UserProfileForm(forms.ModelForm):
	
	telephone = forms.CharField(max_length=15, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Telephone..'}))
	address = forms.CharField(max_length=100, required=True, 
		widget=forms.TextInput(attrs={'placeholder': '*First line of address..'}))
	town = forms.CharField(max_length=100, required=True, 
		widget=forms.TextInput(attrs={'placeholder': '*Town or City..'}))
	county = forms.CharField(max_length=100, required=True, 
		widget=forms.TextInput(attrs={'placeholder': '*County..'}))
	post_code = forms.CharField(max_length=8, required=True, 
		widget=forms.TextInput(attrs={'placeholder': '*Postal Code..'}))
	country = forms.CharField(max_length=100, required=True, 
		widget=forms.Select(attrs={"class": "selection"}, choices=COUNTRIES))


	class Meta:
		model = UserProfile
		fields = ('telephone', 'address', 'town', 'county', 'post_code', 'country' )




'''
Form that uses built-in PasswordResetForm to handel a request to reset password
'''
class RequestPasswordForm(PasswordResetForm):
	
	email = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Email..'}))
	
	class Meta:
		model = User
		fields = ('email',)




'''
Form that uses built-in SetPasswordForm to handel resetting passwords
'''
class ForgottenPasswordForm(SetPasswordForm):
	
	new_password1 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Password..','class':'password'}))
	new_password2 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Confirm Password..','class':'password'}))

	class Meta:
		model = User
		fields = ('password1', 'password2', )




'''
Basic model-form to enable 2-step auth
'''
class TwoStepForm(forms.ModelForm):
	
	two_step_code = forms.CharField(max_length=6, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Code..'}))

	class Meta:
		model = UserToken
		fields = ('two_step_code',)

users/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse
from django.conf import settings
from django.http import JsonResponse
import json

from .models import (
	UserToken
	)

from .mixins import (
	FormErrors,
	RedirectParams,
	TokenGenerator,
	ActivateTwoStep,
	CreateEmail
	)

from .forms import (
	UserForm,
	UserProfileForm,
	ForgottenPasswordForm,
	AuthForm,
	RequestPasswordForm,
	TwoStepForm
	)




'''
Basic view for user sign up
'''
def sign_up(request):
	
	#redirect if user is already signed in
	if request.user.is_authenticated:
		return redirect(reverse('users:account'))

	u_form = UserForm()
	up_form = UserProfileForm()
	result = "error"
	message = "Something went wrong. Please check and try again"

	#Safe guard to stop sign up until API key is added
	if settings.TWILIO_AUTH_TOKEN == "XXX":
		return HttpResponse(
				json.dumps({"result":result, "message": message}),
				content_type="application/json"
				)

	if request.is_ajax() and request.method == "POST":
		u_form = UserForm(data = request.POST)
		up_form = UserProfileForm(data = request.POST)
		
		#if both forms are valid, do something
		if u_form.is_valid() and up_form.is_valid():
			user = u_form.save()

			#commit = False is used as userprofile.user can not be null
			up = up_form.save(commit = False)
			up.user = user
			up.save()


			# Mark user profile as inactive until verified
			user.is_active = False
			user.email = user.username
			user.save()

			#create a new token
			token = TokenGenerator()
			make_token = token.make_token(user)
			url_safe = urlsafe_base64_encode(force_bytes(user.pk))

			#create and sends a SMS code
			sms_code = ActivateTwoStep(user = user, token=make_token)

			result = "perfect"
			message = "We have sent you an SMS"
			context = {"result": result, "message": message, "url_safe": url_safe, "token": make_token}
		else:
			message = FormErrors(u_form, up_form)
			context = {"result": result, "message": message}

		return HttpResponse(
			json.dumps(context),
			content_type="application/json"
			)
		
	context = {'u_form':u_form, 'up_form':up_form}
	return render(request, 'users/sign_up.html', context)




'''
Basic view for user sign in
'''
def sign_in(request):

	#redirect if user is already signed in
	if request.user.is_authenticated:
		return redirect(reverse('users:account'))
	
	a_form = AuthForm()
	result = "error"
	message = "Something went wrong. Please check and try again"

	if request.is_ajax() and request.method == "POST":
		a_form = AuthForm(data = request.POST)
		if a_form.is_valid():
			username = a_form.cleaned_data.get('username')
			password = a_form.cleaned_data.get('password')

			#authenticate Django built in authenticate - https://docs.djangoproject.com/en/3.1/ref/contrib/auth/
			user = authenticate(request, username=username, password=password)
			if user is not None:

				#check to see if 2-step verification is active
				if user.userprofile.two_step_active:
					#create and sends a SMS code
					token = TokenGenerator()
					make_token = token.make_token(user)
					url_safe = urlsafe_base64_encode(force_bytes(user.pk))

					#create and sends a SMS code
					sms_code = ActivateTwoStep(user = user, token=make_token)
					message = 'We have sent you an SMS'
					result = "perfect"
					return HttpResponse(
						json.dumps({"result": result, "message": message, "url_safe":url_safe, "token":make_token}),
						content_type="application/json"
						)
				else:
					login(request, user)
					message = 'You are now logged in'
					result = "perfect"

		else:
			message = FormErrors(a_form)
		
		return HttpResponse(
			json.dumps({"result": result, "message": message}),
			content_type="application/json"
			)
	context = {'a_form':a_form}

	#passes 'token_error' parameter to url to handle a error message
	token_error = request.GET.get("token_error",None)
	if token_error:
		context["token_error"] = "true"
	else:
		context["token_error"] = "false"


	return render(request, 'users/sign_in.html', context)




'''
Basic view for user sign out
'''
def sign_out(request):
	logout(request)
	return redirect(reverse('users:sign-in'))



'''
Basic view for users to request a new password
'''
def forgotten_password(request):

	rp_form = RequestPasswordForm()
	result = "error"
	message = "Something went wrong. Please check and try again"

	if request.is_ajax() and request.method == "POST":
		rp_form = RequestPasswordForm(data = request.POST)

		if rp_form.is_valid():
			
			username = rp_form.cleaned_data.get('email')
			user = User.objects.get(username = username)
			#create a new token
			token = TokenGenerator()
			make_token = token.make_token(user)
			
			ut = UserToken.objects.create(
				user=user,
			 	token = make_token,
			 	is_password = True)

			#send email verification email
			CreateEmail(
				request,
				email_account = "donotreply",
				subject = 'Password reset',
				email = user.username,
				cc = [],
				template = "password_email.html",
				token = make_token,
				url_safe = urlsafe_base64_encode(force_bytes(user.pk))
				)
			result = "perfect"
			message = "You will receive an email to reset your password"			
		else:
			message = FormErrors(rp_form)
		
		return HttpResponse(
			json.dumps({"result": result, "message": message}),
			content_type="application/json"
			)
	context = {'rp_form':rp_form}
	return render(request, 'users/forgotten_password.html', context)





'''
Account view for registered users
'''
@login_required
def account(request):

	if request.method == "POST":
		toggle = request.POST.get("toggle")

		up = request.user.userprofile
		if toggle == "on":
			up.two_step_active = True
		else:
			up.two_step_active = False

		up.save()

		return HttpResponse(
			json.dumps({}),
			content_type="application/json"
			)

	context = {}
	#passes 'verified' parameter to url to handle a success message
	verified = request.GET.get("verified",None)
	if verified:
		context["verified"] = "true"
	else:
		context["verified"] = "false"

	return render(request,'users/account.html', context)




'''
AJAX function to request email view for registered users
'''
@login_required
def email(request):
	
	result = "error"
	message = "Something went wrong. Please check and try again"

	if request.method == "POST":
		
		user = request.user
		#create a new token
		token = TokenGenerator()
		make_token = token.make_token(user)
		url_safe = urlsafe_base64_encode(force_bytes(user.pk))

		#Create a usertoken object to store token
		ut = UserToken.objects.create(
			user=user,
		 	token = make_token,
		 	is_email = True)
		
		
		#send email verification email
		CreateEmail(
			request,
			email_account = "donotreply",
			subject = 'Verify your email',
			email = user.username,
			cc = [],
			template = "verification_email.html",
			token = make_token,
			url_safe = url_safe
			)

		result = "perfect"
		message = "We have sent you an email to verify"
		return HttpResponse(
			json.dumps({"result": result, "message": message}),
			content_type="application/json"
			)


	return HttpResponse(
		json.dumps({"result": result, "message": message}),
		content_type="application/json"
		)






'''
Function view to handle verification tokens
'''
def verification(request, uidb64, token):

	try:
		uid = force_text(urlsafe_base64_decode(uidb64))
		user = User.objects.get(pk=uid)
		ut = UserToken.objects.get(user = user, token = token, is_active = True)
		email_token = ut.is_email
		password_token = ut.is_password

	except(TypeError, ValueError, OverflowError, User.DoesNotExist, UserToken.DoesNotExist):

		#user our RedirectParams function to redirect & append 'token_error' parameter to fire an error message
		return RedirectParams(url = 'users:sign-in', params = {"token_error": "true"})

	#if User & UserToken exist...
	if user and ut:

		# if the token type is_email
		if email_token:

			#deactivate the token now that it has been used
			ut.is_active = False
			ut.save()

			up = user.userprofile
			up.email_verified = True
			up.save()
						
			#login the user
			login(request, user)

			#user our RedirectParams function to redirect & append 'verified' parameter to fire a success message
			return RedirectParams(url = 'users:account', params = {"verified": "true"})
		
		# if the token is a password token 
		elif password_token:

			fp_form = ForgottenPasswordForm(user = user)
			result = "error"
			message = "Something went wrong. Please check and try again"

			if request.is_ajax() and request.method == "POST":
				fp_form = ForgottenPasswordForm(data = request.POST, user = user)

				if fp_form.is_valid():
					
					fp_form.save()
					login(request, user)

					#deactivate the token now that it has been used
					ut.is_active = False
					ut.save()
					message = "Your password has been updated"
					result = "perfect"
								
				else:
					message = FormErrors(rp_form)
				
				return HttpResponse(
					json.dumps({"result": result, "message": message}),
					content_type="application/json"
					)
			context = {'fp_form':fp_form, "uidb64":uidb64, "token":token}
			return render(request, 'users/verification.html', context)

		#else the token is for 2 step verification
		else:
			ts_form = TwoStepForm()
			result = "error"
			message = "Something went wrong. Please check and try again"

			if request.is_ajax() and request.method == "POST":
				ts_form = TwoStepForm(data = request.POST)

				if ts_form.is_valid():
					
					two_step_code = ts_form.cleaned_data.get('two_step_code')

					if two_step_code == ut.two_step_code:
						
						user.is_active = True
						user.save()

users/templates/users/account.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block extend_nav %}

<ul class="sidenav">
  <li><a class="active" href="{% url 'users:account' %}">Demo User Account</a></li>
  <li><a href="{% url 'users:sign-out' %}">Sign out</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Django Twilio 2-Step Verification Demo - User Account</h3>

<div class="container">

  <h4>User account details</h4>
  <table>
    <thead>
      <tr>
        <th>Field</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Username</td>
        {% if request.user.userprofile.email_verified %}
        <td>{{request.user.username}} <b style="color:green">(verified)</b></td>
        {% else %}
        <td>{{request.user.username}} <a href="javascript:void(0)" onclick="EmailVerification()"><b style="color:red">(please verify)</b></a></td>
        {% endif %}      
      </tr>
      <tr>
        <td>Name</td>
        <td>{{request.user.first_name}} {{request.user.last_name}}</td>      
      </tr>
      <tr>
        <td>Telephone</td>
        <td>{{request.user.userprofile.telephone}}</td>      
      </tr>
      <tr>
        <td>Address</td>
        <td>
          <address>
            {{request.user.userprofile.address}}<br>
            {{request.user.userprofile.town}}<br>
            {{request.user.userprofile.county}}<br>
            {{request.user.userprofile.post_code}}<br>
          </address>
        </td>      
      </tr>
      {% if request.user.userprofile.two_step_active %}
      <tr>
        <td id="2-step-term">Turn off 2-Step Verification</td>
        <td>  
          <label class="switch">
            <input id="2-step-toggle" type="checkbox" checked>
            <span class="slider round" onclick="Toggle()"></span>
          </label>
        </td>     
      </tr>
      {% else %}
      <tr>
        <td id="2-step-term">Turn on 2-Step Verification</td>
        <td>  
          <label class="switch">
            <input id="2-step-toggle" type="checkbox">
            <span class="slider round" onclick="Toggle()"></span>
          </label>
        </td>       
      </tr>
      {% endif %}


    </tbody>
  </table>



</div>

<!-- This handels the verified url param & displays a success alert-->
<script type="text/javascript">
  var ver = "{{verified|safe}}"
  if (ver == "true"){
    alert("Thank you, your email has been verified")
  }
</script>

{% endblock %}


{% block extend_footer %}

{% endblock %}

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% include 'users/partials/mixin.html' %}

  <!-- visit https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom to get script-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main.css' %}"></link>

  <!-- This allows us to extend the head scripts in HTML docs that have special requirements-->
  {% block extend_head %}

  {% endblock %}

</head>
<body>

  <!-- This allows us to extend the nav bar in HTML docs that have special requirements-->
  {% block extend_nav %}

  {% endblock %}

  <div class="div-container">
    
    {% include 'users/partials/logo.html' %}

    {% block content %}

    {% endblock %}

  </div>

  <!--visit https://code.jquery.com/ for jquery script-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <!-- This allows us to extend the foot scripts in HTML docs that have special requirements-->
  {% block extend_footer %}

  {% endblock %}

  <script src="{% static 'main.js' %}"></script>
  

</body>
</html>

users/templates/users/forgotten_password.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block extend_nav %}

<ul class="sidenav">
  <li><a href="{% url 'users:sign-in' %}">Demo Sign In</a></li>
  <li><a href="{% url 'users:sign-up' %}">Demo Sign Up</a></li>
  <li><a class="active" href="javascript:void(0)">Demo Forgotten Password</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Django Twilio 2-Step Verification Demo - Forgotten Password</h3>

<div class="container">

  <form id="requestpasswordform" method="POST" action="/forgotten-password">
    {% csrf_token %}
    <label for="email">Username</label>
    {{rp_form.email}}

    <button type="submit">Request New Password</button>
  </form>

  {{rp_form.errors}}

</div>

{% endblock %}


{% block extend_footer %}

{% endblock %}

users/templates/users/sign_in.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block extend_nav %}

<ul class="sidenav">
  <li><a class="active" href="{% url 'users:sign-in' %}">Demo Sign In</a></li>
  <li><a href="{% url 'users:sign-up' %}">Demo Sign Up</a></li>
  <li><a href="{% url 'users:forgotten-password' %}">Demo Forgotten Password</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Django Twilio 2-Step Verification Demo - Sign In</h3>

<div class="container">

  <form id="signinform" method="POST" action="/">
    {% csrf_token %}
    <label for="username">Username</label>
    {{a_form.username}}

    <label for="password">Password</label>
    {{a_form.password}}

    <label class="check-container">Show Passwords
     <input type="checkbox" onclick="showPword()">
     <span class="checkmark"></span>
   </label>

   <button type="submit">Sign in</button>
 </form>

 {{a_form.errors}}

</div>

<!-- This handels the verified url param & displays a success alert-->
<script type="text/javascript">
  var token_error = "{{token_error|safe}}"
  if (token_error == "true"){
    alert("There was a token error. Please try again")
  }
</script>

{% endblock %}


{% block extend_footer %}

{% endblock %}

users/templates/users/sign_up.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}

{% block extend_nav %} 

<ul class="sidenav">
  <li><a href="{% url 'users:sign-in' %}">Demo Sign In</a></li>
  <li><a class="active" href="{% url 'users:sign-up' %}">Demo Sign Up</a></li>
  <li><a href="{% url 'users:forgotten-password' %}">Demo Forgotten Password</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Django Twilio 2-Step Verification Demo - Sign Up</h3>

<div class="container">


  <form id="signupform" method="POST" action="/sign-up">
    {% csrf_token %}

    <label for="username">Username</label>
    {{u_form.username}}

    <label for="password1">Password</label>
    {{u_form.password1}}

    <label for="password2">Confirm Password</label>
    {{u_form.password2}}

    <label class="check-container">Show Passwords
     <input type="checkbox" onclick="showPword()">
     <span class="checkmark"></span>
   </label>

   <label for="first_name">First Name</label>
   {{u_form.first_name}}

   <label for="last_name">Last Name</label>
   {{u_form.last_name}}

   <label for="address">Address</label>
   {{up_form.address}}

   <label for="town">Town/City</label>
   {{up_form.town}}

   <label for="county">County</label>
   {{up_form.county}}

   <label for="post_code">Postal Code</label>
   {{up_form.post_code}}

   <label for="post_code">Country</label>
   {{up_form.country}}

   <label for="telephone">Telephone</label>
   {{up_form.telephone}}

   <button type="submit">Sign up</button>
 </form>

 {{u_form.errors}}
 {{up_form.errors}}

</div>

{% endblock %}

{% block extend_footer %}


{% endblock %}

users/templates/users/two_step_verification.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block extend_nav %}

<ul class="sidenav">
  <li><a class="active" href="javascript:void(0)">Two Step Verification</a></li>
  <li><a href="{% url 'users:sign-in' %}">Demo Sign In</a></li>
  <li><a href="{% url 'users:sign-up' %}">Demo Sign Up</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Django Twilio 2-Step Verification Demo - 2-Step Verification</h3>

<div class="container">

  <form id="twostepform" method="POST" action="/verification/{{uidb64}}/{{token}}/">
    {% csrf_token %}

    <label for="two_step_code">2-Step Code</label>
    {{ts_form.two_step_code}}

   <button type="submit">Verify</button>
 </form>

 {{ts_form.errors}}

</div>

{% endblock %}

{% block extend_footer %}


{% endblock %}

users/templates/users/verification.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block extend_nav %}

<ul class="sidenav">
  <li><a class="active" href="javascript:void(0)">Change Password</a></li>
  <li><a href="{% url 'users:sign-in' %}">Demo Sign In</a></li>
  <li><a href="{% url 'users:sign-up' %}">Demo Sign Up</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Django Twilio 2-Step Verification Demo - Update Password</h3>

<div class="container">

  <form id="updatepasswordform" method="POST" action="/verification/{{uidb64}}/{{token}}/">
    {% csrf_token %}

    <label for="new_password1">Password</label>
    {{fp_form.new_password1}}

    <label for="new_password2">Confirm Password</label>
    {{fp_form.new_password2}}

    <label class="check-container">Show Password
     <input type="checkbox" onclick="showPword()">
     <span class="checkmark"></span>
   </label>

   <button type="submit">Update Password</button>
 </form>

 {{fp_form.errors}}

</div>

{% endblock %}

{% block extend_footer %}


{% endblock %}